version: '3.7'

services:
  postgres:
    container_name: fc_pg
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fc_db
  pgadmin:
    container_name: fc_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
volumes:
  postgres:
  pgadmin:
