export const INVESTMENT_CATEGORIES = {
  CERTIFICATE_OF_DEPOSIT: 'CERTIFICATE_OF_DEPOSIT',
  GOVERNMENT_BOND_FUNDS: 'GOVERNMENT_BOND_FUNDS',
  MONEY_MARKET_ACCOUNT: 'MONEY_MARKET_ACCOUNT',
  RENTAL_HOUSING: 'RENTAL_HOUSING',
  SAVINGS_ACCOUNT: 'SAVINGS_ACCOUNT',
  STOCK_FUND: 'STOCK_FUND',
  TREASURY_SECURITIES: 'TREASURY_SECURITIES',
  OTHER: 'OTHER',
  HEDGE_FUND: 'HEDGE_FUND',
} as const;

export type InvestmentCategory = keyof typeof INVESTMENT_CATEGORIES;

export const INVESTMENT_CATEGORIES_TRANSLATIONS = {
  CERTIFICATE_OF_DEPOSIT: 'Certificate of deposit',
  GOVERNMENT_BOND_FUNDS: 'Government bond funds',
  MONEY_MARKET_ACCOUNT: 'Money market account',
  RENTAL_HOUSING: 'Rental housing',
  SAVINGS_ACCOUNT: 'Savings account',
  STOCK_FUND: 'Stock fund',
  TREASURY_SECURITIES: 'Treasury securities',
  OTHER: 'Other',
  HEDGE_FUND: 'Hedge fund',
} as const;

export const INVESTMENT_CATEGORY_ENTRIES = (Object.keys(
  INVESTMENT_CATEGORIES,
) as InvestmentCategory[]).map((val) => ({
  value: val,
  label: INVESTMENT_CATEGORIES_TRANSLATIONS[val],
}));

export const INVESTMENT_CATEGORY_COLORS = {
  CERTIFICATE_OF_DEPOSIT: '#D53F8C',
  GOVERNMENT_BOND_FUNDS: '#805AD5',
  MONEY_MARKET_ACCOUNT: '#00B5D8',
  RENTAL_HOUSING: '#3182CE',
  SAVINGS_ACCOUNT: '#319795',
  STOCK_FUND: '#38A169',
  TREASURY_SECURITIES: '#ECC94B',
  OTHER: '#718096',
  HEDGE_FUND: '#DD6B20',
} as const;

export const INVESTMENT_CATEGORY_SCHEME_COLORS = {
  CERTIFICATE_OF_DEPOSIT: 'pink',
  GOVERNMENT_BOND_FUNDS: 'purple',
  MONEY_MARKET_ACCOUNT: 'cyan',
  RENTAL_HOUSING: 'blue',
  SAVINGS_ACCOUNT: 'teal',
  STOCK_FUND: 'green',
  TREASURY_SECURITIES: 'yellow',
  OTHER: 'gray',
  HEDGE_FUND: 'orange',
};
