name: Test

on: [push]

jobs:

  app-tests:
    name: Application unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('./application/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run tests
        run: npm run test:cov
        working-directory: ./frontend
      - name: Upload coverage
        uses: codecov/codecov-action@v1

  backend-tests:
    name: Backend unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn verify
        working-directory: ./backend
      - name: Upload coverage
        uses: codecov/codecov-action@v1
