name: Test

on: [ push ]

jobs:
  app-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./frontend
      - name: Run tests
        run: yarn run test:cov
        working-directory: ./frontend
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -D sonar.organization=nalhin
            -D sonar.projectKey=FinanceCalculator_frontend
            -D sonar.sources=src
            -D sonar.tests=src
            -D sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx
            -D sonar.javascript.lcov.reportPaths=coverage/lcov.info
            -D sonar.testExecutionReportPaths=coverage/sonar-report.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v1

  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        working-directory: ./backend
      - name: Upload coverage
        uses: codecov/codecov-action@v1
